// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using meeyland_be.Data;

#nullable disable

namespace meeyland_be.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("meeyland_be.Models.ChatMessage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("AttachmentUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ChatRoomId")
                    .HasColumnType("int");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("SenderId")
                    .HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("ChatRoomId");
                b.HasIndex("SenderId");
                b.ToTable("ChatMessages");
            });

            modelBuilder.Entity("meeyland_be.Models.ChatRoom", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("CreatedByUserId")
                    .HasColumnType("int");

                b.Property<bool>("IsGroup")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.HasIndex("CreatedByUserId");
                b.ToTable("ChatRooms");
            });

            modelBuilder.Entity("meeyland_be.Models.Contact", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("AddedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("ContactUserId")
                    .HasColumnType("int");

                b.Property<int>("OwnerId")
                    .HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("ContactUserId");
                b.HasIndex("OwnerId", "ContactUserId").IsUnique();
                b.ToTable("Contacts");
            });

            modelBuilder.Entity("meeyland_be.Models.RoomMember", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ChatRoomId")
                    .HasColumnType("int");

                b.Property<bool>("IsAdmin")
                    .HasColumnType("bit");

                b.Property<DateTime>("JoinedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("LastReadAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("LastReadMessageId")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("ChatRoomId", "UserId").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("RoomMembers");
            });

            modelBuilder.Entity("meeyland_be.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("AvatarUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("meeyland_be.Models.ChatMessage", b =>
            {
                b.HasOne("meeyland_be.Models.ChatRoom", "ChatRoom")
                    .WithMany("Messages")
                    .HasForeignKey("ChatRoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("meeyland_be.Models.User", "Sender")
                    .WithMany("Messages")
                    .HasForeignKey("SenderId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("ChatRoom");
                b.Navigation("Sender");
            });

            modelBuilder.Entity("meeyland_be.Models.ChatRoom", b =>
            {
                b.HasOne("meeyland_be.Models.User", "CreatedBy")
                    .WithMany()
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("CreatedBy");
            });

            modelBuilder.Entity("meeyland_be.Models.Contact", b =>
            {
                b.HasOne("meeyland_be.Models.User", "ContactUser")
                    .WithMany()
                    .HasForeignKey("ContactUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("meeyland_be.Models.User", "Owner")
                    .WithMany("Contacts")
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("ContactUser");
                b.Navigation("Owner");
            });

            modelBuilder.Entity("meeyland_be.Models.RoomMember", b =>
            {
                b.HasOne("meeyland_be.Models.ChatRoom", "ChatRoom")
                    .WithMany("Members")
                    .HasForeignKey("ChatRoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("meeyland_be.Models.User", "User")
                    .WithMany("RoomMemberships")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("ChatRoom");
                b.Navigation("User");
            });

            modelBuilder.Entity("meeyland_be.Models.ChatRoom", b =>
            {
                b.Navigation("Members");
                b.Navigation("Messages");
            });

            modelBuilder.Entity("meeyland_be.Models.User", b =>
            {
                b.Navigation("Contacts");
                b.Navigation("Messages");
                b.Navigation("RoomMemberships");
            });
#pragma warning restore 612, 618
        }
    }
}
